In [1]:
def train(inputs,b,t,rho,L,n):
    print("Initial bij(Bottom-Up weights)b=",b,'\n')
    print("Initial tji(Top down weights)t=",t,'\n')
    for s in inputs:
        print("S =",s,'\n')
        norm_s=np.sum(s)
        print("||S||-->",norm_s,'\n')
        x=s
        y=np.dot(x,b)
        print("y=bij * x -->",y)
        J=winner(y)
        print("Winner J=",J,'\n')

        xi=s*t[J]
        print("xi =si * tJi =",xi,'\n')
        norm_xi=np.sum(xi)
        print('||xi||-->',norm_xi)
        test_reset=norm_xi/norm_s
        print("||x||/||s||-->",test_reset,'\n')
        print("rho",rho)
        if test_reset >= rho :
            print("Reset is false")
            for i in range(n):
                b[i][J]=(L*xi[i])/((L-1) +norm_xi)
                t[J][i]=xi[i]
            print("bij(new)-->",b,'\n')
                # print("tji(new)--->",t,'\n')



In [2]:
def winner(y):
    j=0
    for i in range(len(y)):
        if y[i]> y[j] :
            j=i
    return j

In [3]:
import numpy as np
inputs=np.array([[0,0,0,1],[0,1,0,1],[0,0,1,1],[1,0,0,0]])
rho=0.4
L=2
n=4
m=3
bottom=1/(1+n)
b=np.full((n,m),bottom)
t=np.full((m,n),1)


In [4]:
train(inputs,b,t,L,n)

TypeError: train() missing 1 required positional argument: 'n'

In [8]:
print(b)
print(t)

[[0.  1.  0.2]
 [0.  0.  0.2]
 [0.  0.  0.2]
 [1.  0.  0.2]]
[[0 0 0 1]
 [1 0 0 0]
 [1 1 1 1]]


In [9]:
b

array([[0. , 1. , 0.2],
       [0. , 0. , 0.2],
       [0. , 0. , 0.2],
       [1. , 0. , 0.2]])

In [23]:
def train(inputs,b,t,rho,L,n):
    print("Initial bij-->",b,'\n')
    print("Initial tji--->",t,'\n')
    for s in inputs:
        print("s--->",s)
        norm_s=np.sum(s)
        x=s
        y=np.dot(x,b)
        print("y=x[i]*bij--->",y,'\n')
        J=winner(y)
        print("J--->",J,'\n')
        xi=x*t[J]
        norm_xi=np.sum(xi)
        print("norm_xi ---->",norm_xi)
        test_reset=norm_xi/norm_s
        print("Test Reset --->",test_reset)
        print("Vigilance Parameter--->",rho)
        if test_reset > rho :
            print("Reset is false")
            for i in range(n):
                b[i][J]=L*xi[i]/(L-1+norm_xi)
                t[J][i]=xi[i]
            print("bij(new)--->",b,'\n')
            print("tji(new)--->",t,'\n')
            


In [24]:
def winner(y):
    j=0
    for i in range(len(y)):
        if y[i]>y[j]:
            j=i
    return j

In [25]:
import numpy as np
inputs=np.array([[0,0,0,1],[0,1,0,1],[0,0,1,1],[1,0,0,0]])
rho=0.4
L=2
n=4
m=3
bottom=1/(1+n)
b=np.full((n,m),bottom)
t=np.full((m,n),1)

In [26]:
train(inputs,b,t,rho,L,n)

Initial bij--> [[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]] 

Initial tji---> [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

s---> [0 0 0 1]
y=x[i]*bij---> [0.2 0.2 0.2] 

J---> 0 

norm_xi ----> 1
Test Reset ---> 1.0
Vigilance Parameter---> 0.4
Reset is false
bij(new)---> [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]] 

tji(new)---> [[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]] 

s---> [0 1 0 1]
y=x[i]*bij---> [1.  0.4 0.4] 

J---> 0 

norm_xi ----> 1
Test Reset ---> 0.5
Vigilance Parameter---> 0.4
Reset is false
bij(new)---> [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]] 

tji(new)---> [[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]] 

s---> [0 0 1 1]
y=x[i]*bij---> [1.  0.4 0.4] 

J---> 0 

norm_xi ----> 1
Test Reset ---> 0.5
Vigilance Parameter---> 0.4
Reset is false
bij(new)---> [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]] 

tji(new)---> [[0 0 0 1]
 [1 1 1 1]
 [1 1 1 1]] 

s---> [1 0 0 0]
y=x[i]*bij---> [0.  0.2 0.2] 

J---> 1 

norm_xi ----> 1
Test Reset ---